### ISSUE TITLE
Build fails on linux PPC & PPC64 missing SkCanvas.h

### ISSUE THREAD

**Issue by rmottola** [rmottola/Arctic-Fox#282]
On Both PPC and PPC64 on Debian compilation fails:

```

87:05.00 In file included from /home/multix/code/Arctic-Fox/gfx/layers/composite/LayerManagerComposite.cpp:15,
87:05.00                  from /home/multix/code/Arctic-Fox/obj-powerpc64-unknown-linux-gnu/gfx/layers/Unified_cpp_gfx_layers5.cpp:29:
87:05.00 /home/multix/code/Arctic-Fox/gfx/layers/composite/PaintCounter.h:12:10: fatal error: skia/include/core/SkCanvas.h: No such file or directory
87:05.00    12 | #include "skia/include/core/SkCanvas.h"
87:05.00       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
87:05.00 compilation terminated.
87:05.00 
87:05.00 In the directory  /home/multix/code/Arctic-Fox/obj-powerpc64-unknown-linux-gnu/gfx/layers
```

compilation on x86/amd64 is fine as well as Mac

**Comment by zephyyy** [comment]
Encountered the same problem while trying to build from the dev branch a few days ago, the same also stands for the 46.3 release.

I have also tried adding `--enable-skia` to mozconfig, but in this case, the build fails with

```
 9:10.14 /var/tmp/portage/www-client/arcticfox-46.3/work/arcticfox-46.3/gfx/skia/skia/include/core/SkImageInfo.h:85:6: error: #error "SK_*32_SHFIT values must correspond to BGRA or RGBA byte order"
 9:10.14    85 |     #error "SK_*32_SHFIT values must correspond to BGRA or RGBA byte order"
 9:10.15       |      ^~~~~
 9:10.16 In file included from /var/tmp/portage/www-client/arcticfox-46.3/work/arcticfox-46.3/gfx/skia/skia/include/core/../gpu/GrColor.h:14,
 9:10.16                  from /var/tmp/portage/www-client/arcticfox-46.3/work/arcticfox-46.3/gfx/skia/skia/include/core/SkShader.h:17,
 9:10.17                  from /var/tmp/portage/www-client/arcticfox-46.3/work/arcticfox-46.3/gfx/skia/skia/include/core/SkImage.h:16,
 9:10.18                  from /var/tmp/portage/www-client/arcticfox-46.3/work/arcticfox-46.3/gfx/skia/skia/include/core/SkCanvas.h:14:
 9:10.18 /var/tmp/portage/www-client/arcticfox-46.3/work/arcticfox-46.3/gfx/skia/skia/include/core/../gpu/GrTypes.h:271:6: error: #error "Skia gpu currently assumes little endian"
 9:10.19   271 |     #error "Skia gpu currently assumes little endian"
 9:10.19       |      ^~~~~
 9:10.20 /var/tmp/portage/www-client/arcticfox-46.3/work/arcticfox-46.3/gfx/skia/skia/include/core/../gpu/GrTypes.h:280:6: error: #error "SK_*32_SHIFT values must correspond to GL_BGRA or GL_RGBA format."
 9:10.21   280 |     #error "SK_*32_SHIFT values must correspond to GL_BGRA or GL_RGBA format."
 9:10.21       |      ^~~~~
 9:10.22 In file included from /var/tmp/portage/www-client/arcticfox-46.3/work/arcticfox-46.3/gfx/skia/skia/include/core/../gpu/GrColor.h:16:
 9:10.23 /var/tmp/portage/www-client/arcticfox-46.3/work/arcticfox-46.3/gfx/skia/skia/include/core/SkColorPriv.h:95:10: error: #error "need 32bit packing to be either RGBA or BGRA"
 9:10.23    95 |         #error "need 32bit packing to be either RGBA or BGRA"
```

**Comment by rmottola** [comment]
Skia is a major blocker for big-endian support (didn't check current code, but it sure was years ago). Don't enable it.

See here:

https://bugs.gentoo.org/607662

**Comment by rmottola** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1319389

**Comment by rmottola** [comment]
https://github.com/rmottola/Arctic-Fox/commit/922666106b8680148254730fb3e829bc3ebf1053

was imported, @zephyyy it should fix the issue about 32bit endianness you see, probably then you will  see the error I see. I don't know, try dev branch.

**Comment by zephyyy** [comment]
Yeah, I saw the same error as you did when I was trying to build the dev branch (or the 46.3 release) without `--enable-skia` on PPC64 BE.
Just started building the dev again, will comment here once it's ready

**Comment by zephyyy** [comment]
Building from commit 46368c1e6cb4c0683abfb75f8d3cbbdd48406a9c, with `--enable-skia` it still fails with
```
 9:19.48 /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/SkImageInfo.h:85:6: error: #error "SK_*32_SHFIT values must correspond to BGRA or RGBA byte order"
 9:19.48    85 |     #error "SK_*32_SHFIT values must correspond to BGRA or RGBA byte order"
 9:19.48       |      ^~~~~
 9:19.48 In file included from /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/../gpu/GrColor.h:14,
 9:19.49                  from /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/SkShader.h:17,
 9:19.49                  from /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/SkImage.h:16,
 9:19.49                  from /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/SkCanvas.h:14:
 9:19.49 /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/../gpu/GrTypes.h:271:6: error: #error "Skia gpu currently assumes little endian"
 9:19.49   271 |     #error "Skia gpu currently assumes little endian"
 9:19.49       |      ^~~~~
 9:19.49 /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/../gpu/GrTypes.h:280:6: error: #error "SK_*32_SHIFT values must correspond to GL_BGRA or GL_RGBA format."
 9:19.49   280 |     #error "SK_*32_SHIFT values must correspond to GL_BGRA or GL_RGBA format."
 9:19.49       |      ^~~~~
 9:19.49 In file included from /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/../gpu/GrColor.h:16:
 9:25.76 /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/SkColorPriv.h:95:10: error: #error "need 32bit packing to be either RGBA or BGRA"
 9:25.77    95 |         #error "need 32bit packing to be either RGBA or BGRA"
 9:25.77       |          ^~~~~
 9:43.39 /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/SkImageInfo.h: In static member function ‘static SkImageInfo SkImageInfo::MakeN32(int, int, SkAlphaType, SkColorProfileType)’:
 9:43.40 /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/SkImageInfo.h:188:43: error: ‘kN32_SkColorType’ was not declared in this scope; did you mean ‘SkColorType’?
 9:43.40   188 |         return SkImageInfo(width, height, kN32_SkColorType, at, pt);
 9:43.40       |                                           ^~~~~~~~~~~~~~~~
 9:43.41       |                                           SkColorType
 9:43.41 /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/SkImageInfo.h: In static member function ‘static SkImageInfo SkImageInfo::MakeN32Premul(int, int, SkColorProfileType)’:
 9:43.41 /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/skia/skia/include/core/SkImageInfo.h:196:43: error: ‘kN32_SkColorType’ was not declared in this scope; did you mean ‘SkColorType’?
 9:43.42   196 |         return SkImageInfo(width, height, kN32_SkColorType, kPremul_SkAlphaType, pt);
 9:43.42       |                                           ^~~~~~~~~~~~~~~~
 9:43.42       |                                           SkColorType
```

Without `--enable-skia`, it fails with `skia/include/core/SkCanvas.h: No such file or directory`, just like before:
```
10:07.62 In file included from /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/layers/composite/LayerManagerComposite.cpp:15,
10:07.62                  from /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/o/gfx/layers/Unified_cpp_gfx_layers5.cpp:29:
10:07.62 /var/tmp/portage/www-client/arcticfox-9999/work/arcticfox-9999/gfx/layers/composite/PaintCounter.h:12:10: fatal error: skia/include/core/SkCanvas.h: No such file or directory
10:07.62    12 | #include "skia/include/core/SkCanvas.h"
10:07.62       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Let me know if you need more testing.

**Comment by foxdrodd** [comment]
can confirm same compile errors when building for sparc64 32bit builds, a bisect from 46.2 to 46.3 showed me  https://github.com/rmottola/Arctic-Fox/commit/e4c21d52e7d9122794272b203cb6ebbb15fb3bcb as the first commit to show "fatal error: skia/include/core/SkCanvas.h: No such file or directory"

**Comment by rmottola** [comment]
@foxdrodd yes, I did a test on sparc64 too and had the same issue. Thank you for bisecting it! Someone did the work for us.

https://bugzilla.mozilla.org/show_bug.cgi?id=1319374

adding to the backport list.

and this also confirms: no skia on little  endian @zephyyy  don't force it.

**Comment by rmottola** [comment]
Bug [1319374](https://bugzilla.mozilla.org/show_bug.cgi?id=1319374) was imported. It fixed PPC build

Linux/sparc still fails for me but for other reasons. I think the original issue is solved. Waiting for your tests @zephyyy  @foxdrodd - maybe #275 needs more work.

**Comment by rmottola** [comment]
specific issue on sparc is #288

**Comment by foxdrodd** [comment]
yes, that fixed the build for me on ppc and sparc. I compiled from dev e0c563e.  Thank you!

**Comment by rmottola** [comment]
@foxdrodd  interesting, that means that you don't reproduce the other sparc error I have. Anyway, this bug is done.

**Comment by zephyyy** [comment]
A bit late to the party, but I just tried building from dev e0c563e71c8a3a0fc5c391090423fe9af8db7948 and yep, it's all good now. Thanks!

<img width="1276" height="702" alt="Image" src="https://github.com/user-attachments/assets/a9379b31-14d9-4ea2-8dd9-c184a65c60c8" />

**Comment by rmottola** [comment]
Wonderful. I fixed the colorskew over X11 export too, so release of 46.4 is out!

**Comment by barracuda156** [comment]
@rmottola Oh, from the release notes (“PPC builds again”) I though it got fixed for Darwin
